<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8d03e234-c34c-41a7-8e54-6ce68401f103</testSuiteGuid>
   <testCaseLink>
      <guid>c64bf0e8-4493-48ea-926b-c73a4d182648</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Test_1_Data_CSV_For_IfElse</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>79cf77db-9714-4ba6-ac1b-1fb1f8674ea7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login_RightAccount_CSV</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d6b5b0-f06c-48d5-9608-15edfcd6ee5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f6b09dd-0f73-4694-bbd8-adc909496639</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d172c7e0-062e-47f9-b293-6c7448428842</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
